### ISSUE TITLE
libsedmlcsP.dll

### ISSUE THREAD

**Issue by sagitter** [fbergmann/libSEDML#10]
Hi all,

```libsedmlcsP.dll``` registration error when i try to use ```gacutil```:

```
gacutil -i build/bindings/csharp/libsedmlcsP.dll -f -package libsedml-sharp -root /home/sagitter/rpmbuild/BUILDROOT/libsedml-0.3.0-7.20150422git235bb5.fc22.x86_64/usr/lib
Failure adding assembly build/bindings/csharp/libsedmlcsP.dll to the cache: Attempt to install an assembly without a strong name
```

Fedora 22 64bit, 
libsedml 235bb5e9af4ce5da59bde2b83e84bf1dbc832ec7,
full build log: https://gist.github.com/sagitter/5e941534afbf516431cf#file-libsedml-build_log

Thanks.

**Comment by fbergmann** [comment]
Just like I don't install the library in the gac, i don't give it a strongname (primarily since i don't pay for a code signing certificate). but you could add that by simply running `sn`. Full information below: 

see also: http://www.mono-project.com/docs/advanced/assemblies-and-the-gac/

so you think this is necessary? Thanks!

**Comment by sagitter** [comment]
>so you think this is necessary?

No, i think.
