### ISSUE TITLE
`xErrorUpper` on curve should be `xError`

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#115]
The specification defines the error attributes as `xError` and `xErrorLower`, but the library uses `xErrorUpper` and `xErrorLower`. Same for the yError attributes on curve.

**Comment by luciansmith** [comment]
I vaguely recall that we did it this way so that if only 'xError' was defined, it was assumed to be symmetric, but now that I'm thinking about it, this seems wrong, not only because that behavior might be surprising, but because it means you can't only set the upper error.

Should we change the spec itself for this one?  If the errors are symmetric, it's simple to just set each to point to the same data generator...

**Comment by matthiaskoenig** [comment]
Yes. I would also favor to update the specification and remove this strange side effects with only setting the xError.

**Comment by luciansmith** [comment]
OK, filed https://github.com/SED-ML/sed-ml/issues/137

Also, I discovered that while the text of the spec talks about 'xError', the UML diagrams have 'xErrorUpper', so something will clearly need to be fixed one way or the other.

**Comment by fbergmann** [comment]
i have to admit when creating the library, i was primarily looking at the UML diagrams. So please let me know what you would prefer. Lets close this issue, if libSEDML is fine, otherwise let me know what to change to what.

**Comment by matthiaskoenig** [comment]
Closing this. The current implementation is correct, this was a specification issue.
