### ISSUE TITLE
Can't figure out how to add namespace in python

### ISSUE THREAD

**Issue by luciansmith** [fbergmann/libSEDML#158]
It seems to me that this should work:

```
import libsedml

sedstr = """<?xml version="1.0" encoding="UTF-8"?>
<sedML xmlns="http://sed-ml.org/" level="1" version="1">
  <listOfModels>
    <model id="model1" language="urn:sedml:language:sbml" source="BIOMD0000000005_url.xml"/>
  </listOfModels>
</sedML>
"""

seddoc = libsedml.readSedMLFromString(sedstr)
sedns = seddoc.getNamespaces()
sedns.add("http://www.sbml.org/sbml/level2/version4", "sbml")
seddoc.setNamespaces(sedns)

print(libsedml.writeSedMLToString(seddoc))
```

However, no new namespace for sbml is added.  Am I doing something wrong, or is there a problem in the library?

**Comment by fbergmann** [comment]
Hello Lucian, 

i would still argue, that we should go with the old definition of SED-ML where, the xpath expression is supposed to be validated in the target document, rather than within the SED-ML document.  As only in the target document you can fully do so. Also if you happen to have a list of 5 models, that use different versions of sbml, in the old interpretation you could always use the `sbml:sbml` ... format, in your new interpretation here, you would have to add 5 additional namespaces. And ever time you add  a new model, you might need to add a new namespace (and use a different prefix ever time). '

But that is despite the point, the answer to your question here is to use `getSedNamespaces` and `addNamespace`. So the complete example turns to: 

```
import libsedml

sedstr = """<?xml version="1.0" encoding="UTF-8"?>
<sedML xmlns="http://sed-ml.org/" level="1" version="1">
  <listOfModels>
    <model id="model1" language="urn:sedml:language:sbml" source="BIOMD0000000005_url.xml"/>
  </listOfModels>
</sedML>
"""

seddoc = libsedml.readSedMLFromString(sedstr)
sedns = seddoc.getSedNamespaces()
sedns.addNamespace("http://www.sbml.org/sbml/level2/version4", "sbml")


print(libsedml.writeSedMLToString(seddoc))

```

**Comment by luciansmith** [comment]
Got it!  Thanks.

I think the problem with the old way of doing things was twofold.  One, it was never encoded in the spec, and was instead a convention, and two, IMO, using xpaths at all was a mistake, particularly when nobody planned to actually support them.  Ah, well...
