### ISSUE TITLE
DataSource.indexSet functions behave strange

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#51]
If no indexSet is set on a DataSource
* `ds.getIndexSet()` returns `` instead of `None` (i.e. empty string)
* `ds.isSetIndexSet()` returns true
This results in strange behavior if one does things like

`if ds.getIndexSet() is None`
or
`if not ds.isSetIndexSet()`

**Comment by fbergmann** [comment]
Hello @matthiaskoenig , since indexSet is of type string, it can never be none, only empty or not. Thus isSetIndexSet compares against the empty string to figure out whether it is empty or not. I'm not sure i see what you would like to see different. 

if i run it in python i get: 

```
In [1]: import libsedml

In [2]: ds = libsedml.SedDataSource()

In [3]: ds.getIndexSet()
Out[3]: ''

In [4]: ds.isSetIndexSet()
Out[4]: False
```


which is what i would expect.

**Comment by matthiaskoenig** [comment]
Sorry, confused this with JSBML (Java) where they handle it like this, i.e. if nothing is set they return `Null` on String attributes. 
Nothing to solve here.
